### ISSUE TITLE
Occasionally unable to sprint

### ISSUE THREAD

**Issue by Skattered** [JohnEdwa/RTAutoSprintExtended#13]
The mod seems to randomly stop working occasionally and not auto sprint, sometimes even stopping you from being able to manually sprint all together. It usually comes back after 10-45 seconds or so. I haven't been able to figure out how to reproduce it unfortunately, however I have only seen it in multiplayer as far as I can remember. Doesn't seem to matter which player tho, we have had it happen to host and multiple clients at different points in the same game.

**Comment by JohnEdwa** [comment]
Sadly there is no "randomly stop working for no reason" block of code that I can remove to fix it, so I would need a bit more information, like what survivor, which skills and so on, to be able to do anything as I haven't had any issues while playing myself.

 In the mean time, manually tapping sprint should make you walk and reset everything, so you at least don't need to wait 45 seconds.

**Comment by Skattered** [comment]
Yeah that's really rough part, sometimes when it happens pressing sprint doesn't make you sprint, you are just locked to walking for that duration (or dying more likely). I know it has happened with the captain and engineer, next time it is happening we can see if we can find any better way to reproduce it

**Comment by JohnEdwa** [comment]
I've finished the rewrite of the mod which completely changes how skills are detected and autosprinting is handled which as a result should, assuming I haven't made any mistakes, pretty much completely eliminate the possibility of these kinds of issues.

Because of that though, the amount of testing I need to do before I can release it to Thunderstore is bonkers, but if you want to help, here's the link https://github.com/JohnEdwa/RTAutoSprintExtended/releases/tag/2.0.0 As an addition I've now made a separate mod/addon that adds support to some custom characters/skills - that can be found here: https://github.com/JohnEdwa/RTAutoSprintAddon/releases/tag/1.0.0
