### ISSUE TITLE
Modded survivors don't auto sprint any more

### ISSUE THREAD

**Issue by argaman123** [JohnEdwa/RTAutoSprintExtended#5]
Any modded survivor I tried (including bandit, akali, and twitch) doesn't auto sprint anymore after the last update. Before that update they all did perfectly, I get it that they are not "supported" but is there no way to make them work at least the same way they used to?

**Comment by Dhs92** [comment]
```1.0.8

    Fixed some 1.0 issues.
    Added Captain.
    Removed the very poor partial support for unspecified/custom survivors as it just breaks things.
```
Sadly it looks like this is intended

**Comment by JohnEdwa** [comment]
It's certainly possible if I can figure a way to make it so that it's not a gamble on if it breaks a character or not. The issue is with skills that work as a "toggle" - think Artificers Ice Wall or Flamethrower. Without a specific workaround, those skills will immediately cast (ice wall) or cancel (flamethrower) if you move, because the mod will make you sprint.
This was the reason Captain was completely broken and unplayable on the old version, because both types of his probe skills work like this.

**Comment by killerjerick** [comment]
Is it possible to just have the sprint on custom characters disabled by default and we can then enable it via console command to see if it works for a specific modded character? Many thanks for all the work you've done on the mod so far, it's an essential mod for sure.

**Comment by JohnEdwa** [comment]
Yeah, I thought about a solution for this and I think I might be able to do a config option that can use the name of the survivor to create a list for what buttons allow/disable autosprint. It would still break the toggle type skills, but it would be a much better solution than having either "isn't allowed at all" and "might completely break a character".

**Comment by JohnEdwa** [comment]
Here's the first draft. I thought how to do it and decided to go with a blacklist, custom survivors are enabled by default and can be disabled from the config file. I'm still trying to figure out how I could make it more configurable than a simple enabled/disabled case, such as adding a check to disable autosprint when holding down a button with a certain survivor, which could be an acceptable workaround for some skills.

I know how to do the in-game part, but I need to somehow make it configurable.

https://github.com/JohnEdwa/RTAutoSprintExtended/releases/tag/1.1.0-RC1

**Comment by killerjerick** [comment]
Unfortunately my knowledge of C# is severely lacking, so I'm not sure of the correct syntax, however, if it was possible to add third party support perhaps those creating custom survivors could simply add a check for your mod in their script, if at all possible adding an exception while a specific skill was being used. One such example I could think of is the Goku mod, which can sprint while flying, but as it's using ki the whole time, the previous system would break thinking it was a skill, but if Kinggrinyov would specify that sprint can work while using the skill, it would mesh well and be less of a headache for you. I'd say you have this luxury as your mod is looked upon as a necessity by many.

Best of luck, if you need any testing, I'd be willing to lend a helping hand whenever available, I reiterate, my C# knowledge is limited but general logic or in-game testing I can help with.

**Comment by mynamaneet** [comment]
Could you maybe add a config option to have the sprint key toggle sprint on/off? So that when you're flying you can quickly toggle off sprint and fly then toggle it back on afterwards. It's not a super good solution but, for me at least, it would be better to be able to toggle than hold down the walk button to allow flying to function better.

**Comment by JohnEdwa** [comment]
Give this one a try, I added a new config option called `ToggleAutoSprint`, which does that. It also overrides HoldSprintToWalk, maybe I'll eventually add the kind of a "tap or hold" thing where tapping toggles and holding doesn't, but that's in the future.

[1_1_3.zip](https://github.com/JohnEdwa/RTAutoSprintExtended/files/5348797/1_1_3.zip)
