### ISSUE TITLE
AutoSprint breaks when using MUL-T's Canister during his primary swap

### ISSUE THREAD

**Issue by itsPoipoi** [JohnEdwa/RTAutoSprintExtended#7]
I notice it when going for Double Rebar loadout, always holding MUL-T's Special to swap primary when it's off cooldown. If I use the canister while holding Special, AutoSprint breaks pretty often, and fixes itself after next Canister use.

**Comment by JohnEdwa** [comment]
Ah, I see the issue, it's the same one that happened with the nailgun, the game allows MUL-T to swap weapons from the temporary disable for the canister firing state (because the canister will shoot if you sprint while aiming it) before AutoSprint has a chance to run the "allow sprinting again" part that comes at the end.

**Comment by itsPoipoi** [comment]
Yeah I figured you'd find the issue quickly since it's similar to the last fix you implemented.

**Comment by JohnEdwa** [comment]
I released the fixed version here https://github.com/JohnEdwa/RTAutoSprintExtended/releases/tag/1.1.2 . I don't have time to play right now so I'll test it tomorrow and if it seems fine, push the release to Thunderstore.

**Comment by itsPoipoi** [comment]
Issue seems resolved. Thank you for your time and effort on this mod!
